document.writeln("<div class=\'footer-wrap\'>");
document.writeln("  <div class=\'container\'>");
document.writeln("    <div class=\'row\'>");
document.writeln("      <div class=\'col-md-3\'>");
document.writeln("        <dl class=\'footer-list\'>");
document.writeln("          <dt class=\'footer-list-item\'>");
document.writeln("            <img class=\'footer-list-logo\' src=\'../ico/logo.png\' alt=\'\' />");
document.writeln("              <div class=\'footer-l\'>");
document.writeln("                <h3>团体心理</h3>");
document.writeln("                <h6>www.tuanti.com.cn</h6>");
document.writeln("              </div>   ");
document.writeln("          </dt>");
document.writeln("        </dl>");
document.writeln("      </div>");
document.writeln("      <div class=\'col-md-6 footer-cen\'>");
document.writeln("        <dl class=\'footer-list\'>");
document.writeln("          <dt class=\'footer-list-item\'>若有问题,请致电客服电话：400-456-123</dt>");
document.writeln("          <dt class=\'footer-list-item\'>Copyright@2016 2009-2017团队活动管理系统 京ICP备07500378号</dt>");
document.writeln("        </dl>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("");
